### PR TITLE
Remove redundant information from setup.py

### PR DESCRIPTION
**Pull request by EwoutH**
A follow-up on #8, to simplify `setup.py` further by removing redundant information from it.

### CODE REVIEW

**Comment by EwoutH** [comment]
CI is green, looks like it's working as expected!

On thing I'm wondering about is how the [`cysetuptools.py`](https://github.com/michelbierlaire/cythonbiogeme/blob/main/cysetuptools.py) file is exactly involved. Is it triggered from the regular `setup.py`?

**Comment by michelbierlaire** [comment]
cysetuptools.py may be a leftover from previous configurations. I am not sure...
I have spent so much time configuring it in the beginning that I tend not to touch it anymore...

**Comment by michelbierlaire** [comment]
With the new configuration, I cannot import cythonbiogeme any more:
`import cythonbiogeme.cythonbiogeme as ee`
`E   ModuleNotFoundError: No module named 'cythonbiogeme.cythonbiogeme'`
Every compiles fine, but the functions defined in cythonbiogeme.pyx are not accessible anymore.
Something must be missing in the `pyproject.toml` or the `setup.py` file, but I was not able to find what.

**Comment by EwoutH** [comment]
I did some testing and I can't resolve this issue, unfortunately.

I would recommend rolling back to 34009d85b05f9f71e1067184b9edd33566180be0 (the last commit before these changes).

Sorry, I should have tested these changes better.

**Comment by EwoutH** [comment]
I opened #14 that does exactly that.

**Comment by michelbierlaire** [comment]
I found the solution. I had to put twice "cythonbiogeme". I don't know why. But it works know. 
 `ext_modules = [`
`        setuptools.Extension(`
 `           "cythonbiogeme.cythonbiogeme",`
 `           sources=[`

**Comment by EwoutH** [comment]
Awesome! That’s way better than reverting everything.

**Pull request merged**
