### PR TITLE
Revert migration to pyproject.toml

### PR DESCRIPTION
**Pull request by EwoutH**
Reverts #8 and #11. See https://github.com/michelbierlaire/cythonbiogeme/pull/11#issuecomment-2198541489 for context.

### CODE REVIEW

**Comment by EwoutH** [comment]
Solution was found, closing.

**Comment by EwoutH** [comment]
I would still recommend rolling back to this version. It might be ugly, but is also proved to be working.

**Comment by michelbierlaire** [comment]
No, I have been working a lot on cythonbiogeme those days, because of the new version of numpy (among other things). I need to move forward, not backward.

**Comment by EwoutH** [comment]
Okay!

**Pull request closed without merging**
