### PR TITLE
Migrate to pyproject.toml

### PR DESCRIPTION
**Pull request by EwoutH**
Initial attempt to migrate the build system to `pyproject.toml`, as is now best practice.

Removes `setup.cfg`, simplifies `setup.py`.

### CODE REVIEW

**Comment by EwoutH** [comment]
@michelbierlaire could you enable the Wheels workflow? https://github.com/michelbierlaire/cythonbiogeme/actions/workflows/wheels.yml

image

**Comment by michelbierlaire** [comment]
Done.

**Comment by EwoutH** [comment]
CI already green. Did not expect that!

**Comment by EwoutH** [comment]
Wheels build! It's a lot simpler than the previous setup.

One thing I noticed is that the wheels are way bigger. Old wheels:
image

New wheels:
image

I think it's either that now there are feels included that previously weren't, or that static linking increased the wheel size.

@michelbierlaire if you have the chance, could you check if these [new wheels](https://github.com/michelbierlaire/cythonbiogeme/actions/runs/9700363285) are working well on your end?

**Comment by EwoutH** [comment]
Thanks for merging! Did you check the wheels though? Because I would like to know that they work, and maybe figure out why they are so much bigger.

**Comment by michelbierlaire** [comment]
Hi,

If I compare those wheels with the previous one, they seem to have a similar size:

(venv312) Downloads/cibw-wheels-macos-14-2-2/>ls -l
total 33408
-rw-r--r--@ 1 bierlair  staff  2860936 Jun 28 06:46 cythonbiogeme-1.0.1-cp310-cp310-macosx_11_0_arm64.whl
-rw-r--r--@ 1 bierlair  staff  2861201 Jun 28 06:46 cythonbiogeme-1.0.1-cp311-cp311-macosx_11_0_arm64.whl
-rw-r--r--@ 1 bierlair  staff  2862394 Jun 28 06:46 cythonbiogeme-1.0.1-cp312-cp312-macosx_11_0_arm64.whl
-rw-r--r--@ 1 bierlair  staff  2861331 Jun 28 06:46 cythonbiogeme-1.0.1-cp39-cp39-macosx_11_0_arm64.whl
-rw-r--r--@ 1 bierlair  staff  2825354 Jun 28 06:46 cythonbiogeme-1.0.1-pp310-pypy310_pp73-macosx_11_0_arm64.whl
-rw-r--r--@ 1 bierlair  staff  2825181 Jun 28 06:46 cythonbiogeme-1.0.1-pp39-pypy39_pp73-macosx_11_0_arm64.whl

(venv312) Downloads/cibw-wheels-macos-14-2-2/>ls -l ../cibw-wheels-macos-13-1/
total 3456
-rw-r--r--@ 1 bierlair  staff  304182 Mar 15 10:36 cythonbiogeme-1.0.1-cp310-cp310-macosx_10_9_x86_64.whl
-rw-r--r--@ 1 bierlair  staff  304891 Mar 15 10:36 cythonbiogeme-1.0.1-cp311-cp311-macosx_10_9_x86_64.whl
-rw-r--r--@ 1 bierlair  staff  306794 Mar 15 10:36 cythonbiogeme-1.0.1-cp312-cp312-macosx_10_9_x86_64.whl
-rw-r--r--@ 1 bierlair  staff  304972 Mar 15 10:36 cythonbiogeme-1.0.1-cp39-cp39-macosx_10_9_x86_64.whl
-rw-r--r--@ 1 bierlair  staff  267232 Mar 15 10:36 cythonbiogeme-1.0.1-pp310-pypy310_pp73-macosx_10_9_x86_64.whl
-rw-r--r--@ 1 bierlair  staff  267085 Mar 15 10:36 cythonbiogeme-1.0.1-pp39-pypy39_pp73-macosx_10_9_x86_64.whl

I have tried to install it, and it seems to work (except that this is the old version). 

(venv312) Downloads/cibw-wheels-macos-14-2-2/>pip install ./cythonbiogeme-1.0.1-cp312-cp312-macosx_11_0_arm64.whl
Processing ./cythonbiogeme-1.0.1-cp312-cp312-macosx_11_0_arm64.whl
Installing collected packages: cythonbiogeme
  Attempting uninstall: cythonbiogeme
    Found existing installation: cythonbiogeme 1.0.3a0
    Uninstalling cythonbiogeme-1.0.3a0:
      Successfully uninstalled cythonbiogeme-1.0.3a0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
biogeme 3.2.14a1 requires cythonbiogeme==1.0.2, but you have cythonbiogeme 1.0.1 which is incompatible.
Successfully installed cythonbiogeme-1.0.1


I am currently updating cythonbiogeme in the develop branch. I'll merge it when it will befully tested.

Thanks a lot for your help.

Michel


> On 28 Jun 2024, at 09:54, Ewout ter Hoeven ***@***.***> wrote:
> 
> 
> Thanks for merging! Did you check the wheels though? Because I would like to know that they work, and maybe figure out why they are so much bigger.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Michel Bierlaire
Transport and Mobility Laboratory
School of Architecture, Civil and Environmental Engineering
EPFL - Ecole Polytechnique Fédérale de Lausanne
http://transp-or.epfl.ch
http://people.epfl.ch/michel.bierlaire

**Comment by EwoutH** [comment]
Okay, thanks for checking! If you experience any problems with them let me know.

If I have time this weekend I might try to get the Windows wheels working. It might now be a bit simpler now that this build setup is simplified.

**Comment by michelbierlaire** [comment]
Thank a lot.

One question:
if you use pyproject.toml, isn't it sufficient to call without arguments?
setuptools.setup()

Michel


> On 28 Jun 2024, at 11:19, Ewout ter Hoeven ***@***.***> wrote:
> 
> 
> Okay, thanks for checking! If you experience any problems with them let me know.
> If I have time this weekend I might try to get the Windows wheels working. It might now be a bit simpler now that this build setup is simplified.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Michel Bierlaire
Transport and Mobility Laboratory
School of Architecture, Civil and Environmental Engineering
EPFL - Ecole Polytechnique Fédérale de Lausanne
http://transp-or.epfl.ch
http://people.epfl.ch/michel.bierlaire

**Comment by EwoutH** [comment]
Good catch. I opened #11 as a follow up.

**Pull request merged**
